"""Generate compact replay cases for the multi-natal orchestrator."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from systems.multi_natal.engine import calculate_natal_synthesis

ROOT = Path(__file__).resolve().parent
SOURCE = "SRC-MULTI-NATAL-PROJECT-SPEC-001"
REVIEWER = {
    "reviewer_id": "deterministic-fixture-generator",
    "role": "calculation",
    "reviewed_at": "2026-07-24",
    "decision": "accepted",
    "notes": (
        "Generated by the committed native calculators; independent domain "
        "review remains pending."
    ),
}
FORBIDDEN = [
    "Do not claim that different systems are equivalent.",
    "Do not count symbolic recurrence as probability or proof.",
    (
        "Do not produce deterministic medical, legal, financial, safety, "
        "employment, or relationship outcomes."
    ),
]


def _expected(result: dict[str, Any]) -> dict[str, Any]:
    cross_checks = result["computed_facts"]["cross_checks"]
    return {
        "included_systems": result["normalized_input"]["included_systems"],
        "system_summaries": result["computed_facts"]["system_summaries"],
        "axis_ids": [
            item["axis_id"] for item in result["computed_facts"]["synthesis_axes"]
        ],
        "utc_all_equal": cross_checks["utc"]["all_equal"],
        "astronomy_status": cross_checks["tropical_astronomy"]["status"],
        "maximum_astronomy_difference_degrees": cross_checks[
            "tropical_astronomy"
        ]["maximum_absolute_difference_degrees"],
    }


def _case(
    *,
    case_id: str,
    title: str,
    category: str,
    raw_input: dict[str, Any],
    rules: list[str],
    disagreements: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    result = calculate_natal_synthesis(raw_input)
    return {
        "case_id": case_id,
        "title": title,
        "system": "multi-natal",
        "lineage": "cross-system-structural-bridge-v0.1",
        "category": category,
        "data_classification": "synthetic",
        "subject": {
            "pseudonymized": True,
            "reliability_grade": "A",
        },
        "raw_input": raw_input,
        "normalized_input": result["normalized_input"],
        "expected_intermediate": {
            "utc_by_system": result["computed_facts"]["cross_checks"]["utc"][
                "utc_by_system"
            ],
            "native_validation": {
                system: chart["validation"]["status"]
                for system, chart in result["computed_facts"]["charts"].items()
                if system != "numerology"
            },
        },
        "expected_output": _expected(result),
        "must_match_rules": rules,
        "allowed_disagreements": disagreements or [],
        "forbidden_conclusions": FORBIDDEN,
        "sources": [
            {
                "source_id": SOURCE,
                "locator": "systems/multi_natal/DATA_CONTRACT.md",
            }
        ],
        "reviewers": [REVIEWER],
    }


def build_cases() -> list[tuple[Path, dict[str, Any]]]:
    standard = {
        "birth_date": "2000-01-01",
        "birth_time": "12:00",
        "birthplace": {
            "name": "Shanghai, China",
            "timezone": "Asia/Shanghai",
            "longitude": 121.4737,
            "latitude": 31.2304,
            "resolution_source": "user_confirmed",
        },
        "calculation_gender": "female",
        "numerology": {
            "name": "Alex Example",
            "mappings": ["pythagorean", "chaldean"],
        },
    }
    dst = {
        "birth_date": "2021-11-07",
        "birth_time": "01:30",
        "birthplace": {
            "name": "New York, New York, United States",
            "timezone": "America/New_York",
            "longitude": -74.006,
            "latitude": 40.7128,
            "resolution_source": "gazetteer",
            "source_url": "https://www.naturalearthdata.com/",
        },
        "calculation_gender": "male",
        "fold": 1,
    }
    apparent = {
        "birth_date": "2001-06-21",
        "birth_time": "23:30",
        "birthplace": {
            "name": "Urumqi, Xinjiang, China",
            "timezone": "Asia/Shanghai",
            "longitude": 87.6168,
            "latitude": 43.8256,
            "resolution_source": "user_confirmed",
        },
        "calculation_gender": "female",
        "policies": {
            "east_asian_time_basis": "apparent_solar",
            "bazi_day_boundary": "zi_initial",
            "ziwei_late_zi_policy": "next_day",
            "vedic_lineages": ["parashari", "jaimini", "kp"],
        },
    }
    return [
        (
            ROOT / "golden" / "CASE-MULTI-NATAL-STANDARD-001.json",
            _case(
                case_id="CASE-MULTI-NATAL-STANDARD-001",
                title="All core birth systems plus explicit dual numerology",
                category="standard",
                raw_input=standard,
                rules=[
                    "MULTI-NATAL-ROUTING-001",
                    "MULTI-NATAL-SUMMARY-001",
                    "MULTI-NATAL-ASTRONOMY-CHECK-001",
                    "MULTI-NATAL-BRIDGE-001",
                    "MULTI-NATAL-NUMEROLOGY-001",
                ],
            ),
        ),
        (
            ROOT / "edge_cases" / "CASE-MULTI-NATAL-EDGE-DST-FOLD-001.json",
            _case(
                case_id="CASE-MULTI-NATAL-EDGE-DST-FOLD-001",
                title="Ambiguous civil time resolved with explicit fold",
                category="edge_case",
                raw_input=dst,
                rules=[
                    "MULTI-NATAL-ROUTING-001",
                    "MULTI-NATAL-ASTRONOMY-CHECK-001",
                    "MULTI-NATAL-BRIDGE-001",
                ],
            ),
        ),
        (
            ROOT
            / "disputes"
            / "CASE-MULTI-NATAL-DISPUTE-TIME-BASIS-001.json",
            _case(
                case_id="CASE-MULTI-NATAL-DISPUTE-TIME-BASIS-001",
                title="Explicit apparent-solar East Asian path near late Zi",
                category="dispute",
                raw_input=apparent,
                rules=[
                    "MULTI-NATAL-ROUTING-001",
                    "MULTI-NATAL-ASTRONOMY-CHECK-001",
                    "MULTI-NATAL-BRIDGE-001",
                ],
                disagreements=[
                    {
                        "dispute_id": "DSP-MULTI-NATAL-COMPARABILITY-001",
                        "field_path": "normalized_input.policies.east_asian_time_basis",
                        "allowed_values": ["civil", "apparent_solar"],
                    }
                ],
            ),
        ),
    ]


def main() -> None:
    for path, document in build_cases():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(document, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
            newline="\n",
        )


if __name__ == "__main__":
    main()
